//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ayellet.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AyelletEntities : DbContext
    {
        public AyelletEntities()
            : base("name=AyelletEntities")
        {

        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<ContactFollowup> ContactFollowup { get; set; }
        public virtual DbSet<Embed> Embed { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<ProjectIntersted> ProjectIntersted { get; set; }
        public virtual DbSet<ProjectVolunteer> ProjectVolunteer { get; set; }
        public virtual DbSet<RelatedPerson> RelatedPerson { get; set; }
        public virtual DbSet<RelationContact> RelationContact { get; set; }
        public virtual DbSet<Relationship> Relationship { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
