//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ayellet.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> RelatedPersonID { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> IsNewlater { get; set; }
        public Nullable<bool> IsVolunteer { get; set; }
    }
}
