//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ayellet.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectVolunteer
    {
        public int ID { get; set; }
        public Nullable<int> ContactID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string Details { get; set; }
        public Nullable<int> AreaID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
